title: Public Sans
baseurl: ""
url: ""

exclude:
  - site-assets/js/src
  - Gemfile*
  - node_modules
  - package*.json
  - README.md
  - vendor
  - webpack.config.js
  - examples
  - fonts/_archive
  - fonts/afm
  - fonts/otf
  - fonts/ufo
  - fonts/variable
  - specimens
  - source
