title: Public Sans
description: A strong, neutral, open source typeface for text or display.
canonical_url: https://public-sans.digital.gov

exclude:
  - site-assets/js/src
  - Gemfile*
  - node_modules
  - package*.json
  - README.md
  - vendor
  - webpack.config.js
  - examples
  - fonts/_archive
  - fonts/afm
  - fonts/otf
  - fonts/ufo
  - fonts/variable
  - specimens
  - source
  - .DS_Store
  - CONTRIBUTING.md
  - FONTLOG.txt
  - Gemfile
  - OFL.txt
  - README.md
  - build.sh
  - Gemfile.lock
  - gulpfile.js
  - package-lock.json
  - package.json
